# Generated by Django 5.1.1 on 2024-10-03 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='programming_images',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
