# Generated by Django 5.1.1 on 2024-10-03 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_programminglanguage_programming_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programminglanguage',
            name='programming_images',
        ),
        migrations.AddField(
            model_name='programminglanguage',
            name='image',
            field=models.ImageField(blank=True, upload_to='programming_languages/'),
        ),
    ]
