# Generated by Django 5.1.1 on 2024-10-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_remove_programminglanguage_programming_images_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='image',
            field=models.ImageField(blank=True, upload_to='{% static /programming_languages/ %}'),
        ),
    ]
