# Generated by Django 5.1.1 on 2024-10-03 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0009_alter_programminglanguage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programminglanguage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
