# Generated by Django 5.1.1 on 2024-10-04 12:16

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0012_alter_programminglanguage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='work',
            name='work_images',
            field=models.ImageField(blank=True, null=True, upload_to='work/'),
        ),
    ]
