# Generated by Django 5.1.1 on 2024-10-04 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0015_rename_created_date_education_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='grade',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
