# Generated by Django 5.1.1 on 2024-10-04 15:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0016_education_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='date',
        ),
        migrations.AddField(
            model_name='education',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='education',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
