# Generated by Django 5.1.1 on 2024-10-04 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0017_remove_education_date_education_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
