# Generated by Django 4.2.17 on 2025-01-06 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0022_certifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='programminglanguage',
            name='icon',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
