# Generated by Django 5.1.4 on 2025-01-07 20:45

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0025_category_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='post',
            name='last_modified',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
