# Generated by Django 5.1.4 on 2025-01-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0026_alter_post_created_on_alter_post_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='Short',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
