# Generated by Django 5.1.4 on 2025-01-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0027_post_short'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='Short',
            new_name='short',
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
