# Generated by Django 5.1.4 on 2025-01-08 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0029_category_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='blog/'),
        ),
    ]
